wallpaper {
    monitor = DP-1
    path = /home/hntr/.local/share/wallpapers/cool-castle.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-2
    path = /home/hntr/.local/share/wallpapers/cool-castle.png
    fit_mode = cover
}
